services:
  airflow:
    build: .
    container_name: lumi-airflow
    ports:
      - "8080:8080"
    volumes:
      - ./dags:/opt/airflow/dags
      - ../sample-data:/opt/airflow/data:ro
      - ../beam-job/target:/opt/airflow/beam
      - ../split-output:/opt/airflow/split
      - ./errors:/opt/airflow/errors
      - ./logs:/opt/airflow/logs
    environment:
      - _AIRFLOW_WWW_USER_USERNAME=${USERNAME}
      - _AIRFLOW_WWW_USER_PASSWORD=${PASSWORD}
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION=False
      - AIRFLOW__API__AUTH_BACKENDS=airflow.api.auth.backend.basic_auth,airflow.api.auth.backend.session
      - DB_URL=${DB_URI}
      - DB_USERNAME=${DB_USER}
      - DB_PASSWORD=${DB_PASS}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command: standalone
